export const events = [
  {
    id: 1,
    name: "서강어택",
    date: "9.19 ~ 9.21 18:00~20:00",
    src: "main_banner1.PNG",
    detail: "디테일한 설명은 생략한다.",
  },
  {
    id: 2,
    name: "서강가왕",
    date: "9.22",
    src: "main_banner2.PNG",
    detail: "디테일한 설명은 생략한다.",
  },
];

export const schedules = [
  {
    id: 1,
    name: "빅뱅",
    date: "9.19",
    day: 1,
    detail: "디테일한 설명은 생략한다.",
  },
  {
    id: 2,
    name: "투애니원",
    date: "9.20",
    day: 2,
    detail: "디테일한 설명은 생략한다.",
  },
  {
    id: 3,
    name: "에스파",
    date: "9.21",
    day: 3,
    detail: "디테일한 설명은 생략한다.",
  },
  {
    id: 4,
    name: "아이브",
    date: "9.22",
    day: 4,
    detail: "디테일한 설명은 생략한다.",
  },
  {
    id: 5,
    name: "에이샙라키",
    date: "9.23",
    day: 5,
    detail: "디테일한 설명은 생략한다.",
  },
  {
    id: 6,
    name: "캔드릭 라마",
    date: "9.20",
    day: 2,
    detail: "디테일한 설명은 생략한다.",
  },
];

export const foods = [
  {
    id: 1,
    menu: "닭꼬치",
    name: "짱츄닭",
    date: "9.19",
    day: 1,
    detail: "디테일한 설명은 생략한다.",
  },
  {
    id: 2,
    menu: "핫도그",
    name: "뉴요커 핫도그",
    date: "9.19",
    day: 1,
    detail: "디테일한 설명은 생략한다.",
  },
  {
    id: 3,
    menu: "불초밥",
    name: "흔남스시",
    date: "9.19",
    day: 1,
    detail: "디테일한 설명은 생략한다.",
  },
  {
    id: 4,
    menu: "타코야끼",
    name: "푸드진열장",
    date: "9.19",
    day: 1,
    detail: "디테일한 설명은 생략한다.",
  },
  {
    id: 5,
    menu: "와플",
    name: "핫플",
    date: "9.19",
    day: 1,
    detail: "디테일한 설명은 생략한다.",
  },
  {
    id: 6,
    menu: "츄러스",
    name: "부부 츄러스",
    date: "9.19",
    day: 1,
    detail: "디테일한 설명은 생략한다.",
  },
  {
    id: 7,
    menu: "닭강정",
    name: "블랙키친",
    date: "9.19",
    day: 1,
    detail: "디테일한 설명은 생략한다.",
  },
  {
    id: 8,
    menu: "칵테일음료",
    name: "체리블라썸/건다방",
    date: "9.19",
    day: 1,
    detail: "디테일한 설명은 생략한다.",
  },
  {
    id: 9,
    menu: "곱창볶음",
    name: "곱창좋은날",
    date: "9.19",
    day: 1,
    detail: "디테일한 설명은 생략한다.",
  },
  {
    id: 10,
    menu: "칠리,크림새우",
    name: "스낵런",
    date: "9.19",
    day: 1,
    detail: "디테일한 설명은 생략한다.",
  },
];

export const fleas = [
  {
    id: 1,
    name: "벼룩맨의 벼룩벼룩",
    date: "9.19",
    day: 1,
    detail: "디테일한 설명은 생략한다.",
  },
  {
    id: 2,
    name: "멋진 골동품",
    date: "9.20",
    day: 2,
    detail: "디테일한 설명은 생략한다.",
  },
];
