export const events = [
  {
    id: 1,
    name: "서강어택",
    date: "9.19 ~ 9.21 18:00~20:00",
    src: "main_banner1.PNG",
    detail: "디테일한 설명은 생략한다.",
  },
  {
    id: 2,
    name: "서강가왕",
    date: "9.22",
    src: "main_banner2.PNG",
    detail: "디테일한 설명은 생략한다.",
  },
];

export const schedules = [
  {
    id: 1,
    name: "빅뱅",
    date: "9.19",
    day: 1,
    detail: "디테일한 설명은 생략한다.",
  },
  {
    id: 2,
    name: "투애니원",
    date: "9.20",
    day: 2,
    detail: "디테일한 설명은 생략한다.",
  },
  {
    id: 3,
    name: "에스파",
    date: "9.21",
    day: 3,
    detail: "디테일한 설명은 생략한다.",
  },
  {
    id: 4,
    name: "아이브",
    date: "9.22",
    day: 4,
    detail: "디테일한 설명은 생략한다.",
  },
  {
    id: 5,
    name: "에이샙라키",
    date: "9.23",
    day: 5,
    detail: "디테일한 설명은 생략한다.",
  },
  {
    id: 6,
    name: "캔드릭 라마",
    date: "9.20",
    day: 2,
    detail: "디테일한 설명은 생략한다.",
  },
];

export const foods = [
  {
    id: 1,
    menu: "닭꼬치",
    name: "짱츄닭",
    date: "9.19",
    day: 1,
    detail: "디테일한 설명은 생략한다.",
  },
  {
    id: 2,
    menu: "핫도그",
    name: "뉴요커 핫도그",
    date: "9.19",
    day: 1,
    detail: "디테일한 설명은 생략한다.",
  },
  {
    id: 3,
    menu: "불초밥",
    name: "흔남스시",
    date: "9.19",
    day: 1,
    detail: "디테일한 설명은 생략한다.",
  },
  {
    id: 4,
    menu: "타코야끼",
    name: "푸드진열장",
    date: "9.19",
    day: 1,
    detail: "디테일한 설명은 생략한다.",
  },
  {
    id: 5,
    menu: "와플",
    name: "핫플",
    date: "9.19",
    day: 1,
    detail: "디테일한 설명은 생략한다.",
  },
  {
    id: 6,
    menu: "츄러스",
    name: "부부 츄러스",
    date: "9.19",
    day: 1,
    detail: "디테일한 설명은 생략한다.",
  },
  {
    id: 7,
    menu: "닭강정",
    name: "블랙키친",
    date: "9.19",
    day: 1,
    detail: "디테일한 설명은 생략한다.",
  },
  {
    id: 8,
    menu: "칵테일음료",
    name: "체리블라썸/건다방",
    date: "9.19",
    day: 1,
    detail: "디테일한 설명은 생략한다.",
  },
  {
    id: 9,
    menu: "곱창볶음",
    name: "곱창좋은날",
    date: "9.19",
    day: 1,
    detail: "디테일한 설명은 생략한다.",
  },
  {
    id: 10,
    menu: "칠리,크림새우",
    name: "스낵런",
    date: "9.19",
    day: 1,
    detail: "디테일한 설명은 생략한다.",
  },
];

export const fleas = [
  {
    //월화수
    id: 1,
    name: "(주)피플밤",
    date: "9.19 - 9.21",
    day: [1,2,3],
    detail: "젤라또",
  },
  {
    id: 2,
    name: "진티엔리밍",
    date: "9.19 - 9.21",
    day: [1,2,3],
    detail: "악세사리",
  },
  {
    id: 3,
    name: "원더우먼",
    date: "9.19 - 9.21",
    day: [1,2,3],
    detail: "쥬얼리",
  },
  {
    id: 4,
    name: "JiSis",
    date: "9.19 - 9.21",
    day: [1,2,3],
    detail: "쥬얼리",
  },
  {
    id: 5,
    name: "나다스토리",
    date: "9.19 - 9.21",
    day: [1,2,3],
    detail: "심리상담",
  },
  {
    id: 6,
    name: "베베시엥",
    date: "9.19 - 9.21",
    day: [1,2,3],
    detail: "펫 악세사리",
  },
  {
    id: 7,
    name: "제이얼리",
    date: "9.19 - 9.21",
    day: [1,2,3],
    detail: "악세사리",
  },
  {
    id: 8,
    name: "코지콤마",
    date: "9.19 - 9.21",
    day: [1,2,3],
    detail: "파우치",
  },
  {
    id: 9,
    name: "비쥬마켓",
    date: "9.19 - 9.21",
    day: [1,2,3],
    detail: "악세사리",
  },
  {
    id: 10,
    name: "3분 수채 초상화",
    date: "9.19 - 9.21",
    day: [1,2,3],
    detail: "캐리커쳐",
  },
  {
    id: 11,
    name: "오브제베이킹스튜디오",
    date: "9.19 - 9.21",
    day: [1,2,3],
    detail: "디저트",
  },
  {
    id: 12,
    name: "스튜디오 늘",
    date: "9.19 - 9.21",
    day: [1,2,3],
    detail: "악세사리",
  },
  {
    id: 13,
    name: "캐리커쳐",
    date: "9.19 - 9.21",
    day: [1,2,3],
    detail: "체험",
  },
  {
    id: 14,
    name: "ZEEMA",
    date: "9.19 - 9.21",
    day: [1,2,3],
    detail: "쥬얼리",
  },
  {
    id: 15,
    name: "짙은달",
    date: "9.19 - 9.21",
    day: [1,2,3],
    detail: "소품",
  },
  {
    id: 16,
    name: "밤비하우스",
    date: "9.19 - 9.21",
    day: [1,2,3],
    detail: "키덜트 캐릭터 용품",
  },
  {
    id: 17,
    name: "제이앤밸류",
    date: "9.19 - 9.21",
    day: [1,2,3],
    detail: "악세사리",
  },
  {
    id: 18,
    name: "가은 스튜디오",
    date: "9.19 - 9.21",
    day: [1,2,3],
    detail: "핸드메이드 소품",
  },
  {
    id: 19,
    name: "화이팅",
    date: "9.19 - 9.21",
    day: [1,2,3],
    detail: "빈티지",
  },
  {
    id: 20,
    name: "이소영",
    date: "9.19 - 9.21",
    day: [1,2,3],
    detail: "악세사리",
  },

  //목금
  {
    id: 1,
    name: "은율",
    date: "9.22 - 9.23",
    day: [4,5],
    detail: "악세사리",
  },
  {
    id: 2,
    name: "란동산",
    date: "9.22 - 9.23",
    day: [4,5],
    detail: "패션 잡화",
  },
  {
    id: 3,
    name: "(주)피플팜",
    date: "9.22 - 9.23",
    day: [4,5],
    detail: "식품",
  },
  {
    id: 4,
    name: "진티엔리밍",
    date: "9.22 - 9.23",
    day: [4,5],
    detail: "악세사리",
  },
  {
    id: 5,
    name: "원더우먼",
    date: "9.22 - 9.23",
    day: [4,5],
    detail: "쥬얼리",
  },
  {
    id: 6,
    name: "Jisis",
    date: "9.22 - 9.23",
    day: [4,5],
    detail: "쥬얼리",
  },
  {
    id: 7,
    name: "나다스토리",
    date: "9.22 - 9.23",
    day: [4,5],
    detail: "심리상담",
  },
  {
    id: 8,
    name: "베베시앵",
    date: "9.22 - 9.23",
    day: [4,5],
    detail: "펫 악세사리",
  },
  {
    id: 9,
    name: "제이얼리",
    date: "9.22 - 9.23",
    day: [4,5],
    detail: "악세사리",
  },
  {
    id: 10,
    name: "코지콤마",
    date: "9.22 - 9.23",
    day: [4,5],
    detail: "파우치",
  },
  {
    id: 11,
    name: "그릭팩토리",
    date: "9.22 - 9.23",
    day: [4,5],
    detail: "식품",
  },
  {
    id: 12,
    name: "3분 수채 초상화",
    date: "9.22 - 9.23",
    day: [4,5],
    detail: "캐리커쳐",
  },
  {
    id: 13,
    name: "shushu",
    date: "9.22 - 9.23",
    day: [4,5],
    detail: "악세사리",
  },
  {
    id: 14,
    name: "낫뚤공방",
    date: "9.22 - 9.23",
    day: [4,5],
    detail: "향수",
  },
  {
    id: 15,
    name: "빈티지리버스",
    date: "9.22 - 9.23",
    day: [4,5],
    detail: "패션",
  },
  {
    id: 16,
    name: "ARO STUDIO",
    date: "9.22 - 9.23",
    day: [4,5],
    detail: "헤나, 타투 스티커",
  },
  {
    id: 17,
    name: "요키네",
    date: "9.22 - 9.23",
    day: [4,5],
    detail: "의류",
  },
  {
    id: 18,
    name: "이조나샵",
    date: "9.22 - 9.23",
    day: [4,5],
    detail: "의류",
  },
  {
    id: 19,
    name: "허밍브래싱",
    date: "9.22 - 9.23",
    day: [4,5],
    detail: "문구류",
  },
  {
    id: 20,
    name: "FeMALE DDANG",
    date: "9.22 - 9.23",
    day: [4,5],
    detail: "도자기 주얼리/소품",
  },
  {
    id: 21,
    name: "샤인컬러",
    date: "9.22 - 9.23",
    day: [4,5],
    detail: "의류",
  },
  {
    id: 22,
    name: "아라비티",
    date: "9.22 - 9.23",
    day: [4,5],
    detail: "음료",
  },
  {
    id: 23,
    name: "취향제작실",
    date: "9.22 - 9.23",
    day: [4,5],
    detail: "악세사리/잡화",
  },
  {
    id: 24,
    name: "캐리커쳐",
    date: "9.22 - 9.23",
    day: [4,5],
    detail: "체험",
  },
  {
    id: 25,
    name: "스튜디오 늘",
    date: "9.22 - 9.23",
    day: [4,5],
    detail: "악세사리",
  },
  {
    id: 26,
    name: "오브제 베이킹 스튜디오",
    date: "9.22 - 9.23",
    day: [4,5],
    detail: "디저트",
  },
  {
    id: 27,
    name: "Carepull",
    date: "9.22 - 9.23",
    day: [4,5],
    detail: "원예",
  },
  {
    id: 28,
    name: "밍블밍블",
    date: "9.22 - 9.23",
    day: [4,5],
    detail: "잡화",
  },
];
