export const events = [
  {
    id: 1,
    name: "서강어택",
    date: "9.19 ~ 9.21 (18:00~20:00)",
    src: "main_banner1.png",
    place: "체육관",
    detail: "디테일한 설명은 생략한다.",
  },
  {
    id: 2,
    name: "서강가왕",
    date: "9.22",
    src: "main_banner2.png",
    place: "대운동장",
    detail: "디테일한 설명은 생략한다.",
  },
  {
    id: 3,
    name: "서강, 좀비의 집",
    date: "9.20 ~ 9.21 (19:00~22:00)",
    src: "main_banner3.png",
    place: "청년광장",
    detail: "디테일한 설명은 생략한다.",
  },
];

export const schedules = [
  {
    id: 1,
    name: "풍연",
    date: "9.19 Mon",
    place: "청년광장",
    type: "동아리 공연",
    time: "18:00-19:00",
    day: 1,
    backgroundImage: `${process.env.PUBLIC_URL}/schedule/풍연.png`,
  },
  {
    id: 2,
    name: "서강진스",
    date: "9.22 Thu",
    place: "청년광장",
    type: "버스킹 공연",
    time: "쉬는시간",
    day: 4,
    backgroundImage: `${process.env.PUBLIC_URL}/schedule/서강진스.png`,
  },
  {
    id: 3,
    name: "사발로마",
    day: 4,
    backgroundImage: `${process.env.PUBLIC_URL}/schedule/사발로마.png`,
  },
  {
    id: 4,
    name: "온빛",
    day: 4,
    backgroundImage: `${process.env.PUBLIC_URL}/schedule/온빛.png`,
  },
  {
    id: 5,
    name: "박장대소",
    day: 4,
    backgroundImage: `${process.env.PUBLIC_URL}/schedule/박장대소.png`,
  },
  {
    id: 6,
    name: "서강 가왕",
    place: "대운동장",
    type: "서강 가왕",
    time: "19:00-21:00",
    day: 4,
    backgroundImage: `${process.env.PUBLIC_URL}/schedule/서강가왕.jpg`,
  },
  {
    id: 7,
    name: "GUESS WHO?",
    type: "연예인 공연",
    time: "21:00-22:00",
    day: 4,
    backgroundImage: `${process.env.PUBLIC_URL}/schedule/콜드.jpg`,
  },
  {
    id: 8,
    name: "민경훈",
    day: 4,
    backgroundImage: `${process.env.PUBLIC_URL}/schedule/민경훈.jpg`,
  },
  {
    id: 9,
    name: "이승원",
    date: "9.23 Fri",
    place: "청년광장",
    type: "버스킹 공연",
    time: "쉬는시간",
    day: 5,
    backgroundImage: `${process.env.PUBLIC_URL}/schedule/이승원.png`,
  },
  {
    id: 10,
    name: "크레센도",
    day: 5,
    backgroundImage: `${process.env.PUBLIC_URL}/schedule/크레센도.png`,
  },
  {
    id: 11,
    name: "크레이즈",
    day: 5,
    backgroundImage: `${process.env.PUBLIC_URL}/schedule/크레이즈.png`,
  },
  {
    id: 12,
    name: "풍물패연합",
    place: "대운동장",
    type: "동아리 공연",
    time: "16:00-20:00",
    day: 5,
    backgroundImage: `${process.env.PUBLIC_URL}/schedule/풍연.png`,
  },
  {
    id: 13,
    name: "샥",
    day: 5,
    backgroundImage: `${process.env.PUBLIC_URL}/schedule/샥 장표.png`,
  },
  {
    id: 14,
    name: "마이티",
    day: 5,
    backgroundImage: `${process.env.PUBLIC_URL}/schedule/마이티 장표.jpeg`,
  },
  {
    id: 15,
    name: "에밀레",
    day: 5,
    backgroundImage: `${process.env.PUBLIC_URL}/schedule/에밀레 장표.jpeg`,
  },
  {
    id: 16,
    name: "광야",
    day: 5,
    backgroundImage: `${process.env.PUBLIC_URL}/schedule/광야 장표.png`,
  },
  {
    id: 17,
    name: "맥박",
    day: 5,
    backgroundImage: `${process.env.PUBLIC_URL}/schedule/맥박 장표.jpeg`,
  },
  {
    id: 18,
    name: "킨젝스",
    day: 5,
    backgroundImage: `${process.env.PUBLIC_URL}/schedule/킨젝스 장표.jpeg`,
  },
  {
    id: 19,
    name: "어비스",
    day: 5,
    backgroundImage: `${process.env.PUBLIC_URL}/schedule/어비스 장표 (검정색).jpeg`,
  },
  {
    id: 20,
    name: "메시지",
    day: 5,
    backgroundImage: `${process.env.PUBLIC_URL}/schedule/메시지 장표.jpeg`,
  },
  {
    id: 21,
    name: "트라이파시",
    type: "트라이파시",
    time: "20:05-20:35",
    day: 5,
    backgroundImage: `${process.env.PUBLIC_URL}/schedule/트라이파시 장표.jpeg`,
  },
  {
    id: 22,
    name: "홀리뱅",
    type: "연예인 공연",
    time: "20:35-23:00",
    day: 5,
    backgroundImage: `${process.env.PUBLIC_URL}/schedule/홀리뱅.jpeg`,
  },
  {
    id: 23,
    name: "MVP",
    day: 5,
    backgroundImage: `${process.env.PUBLIC_URL}/schedule/MVP.jpeg`,
  },
  {
    id: 24,
    name: "GUESS WHO?",
    day: 5,
    backgroundImage: `${process.env.PUBLIC_URL}/schedule/박재범.jpg`,
  },
  {
    id: 25,
    name: "9.20 Tue",
    date: "9.20 Tue",
    day: 2,
    backgroundImage: `${process.env.PUBLIC_URL}/schedule/9.20.png`,
  },
  {
    id: 26,
    name: "9.21 Wed",
    date: "9.21 Wed",
    day: 3,
    backgroundImage: `${process.env.PUBLIC_URL}/schedule/9.21.png`,
  },
];

export const foods = [
  {
    id: 1,
    menu: "닭꼬치",
    name: "짱츄닭",
    date: "9.19~9.23",
    day: 1,
    detail: "디테일한 설명은 생략한다.",
  },
  {
    id: 2,
    menu: "핫도그",
    name: "뉴요커 핫도그",
    date: "9.19~9.23",
    day: 1,
    detail: "디테일한 설명은 생략한다.",
  },
  {
    id: 3,
    menu: "불초밥",
    name: "흔남스시",
    date: "9.19~9.23",
    day: 1,
    detail: "디테일한 설명은 생략한다.",
  },
  {
    id: 4,
    menu: "타코야끼",
    name: "푸드진열장",
    date: "9.19~9.23",
    day: 1,
    detail: "디테일한 설명은 생략한다.",
  },
  {
    id: 5,
    menu: "와플",
    name: "핫플",
    date: "9.19~9.23",
    day: 1,
    detail: "디테일한 설명은 생략한다.",
  },
  {
    id: 6,
    menu: "츄러스",
    name: "부부 츄러스",
    date: "9.19~9.23",
    day: 1,
    detail: "디테일한 설명은 생략한다.",
  },
  {
    id: 7,
    menu: "닭강정",
    name: "블랙키친",
    date: "9.19~9.23",
    day: 1,
    detail: "디테일한 설명은 생략한다.",
  },
  {
    id: 8,
    menu: "칵테일음료",
    name: "체리블라썸/건다방",
    date: "9.19~9.23",
    day: 1,
    detail: "디테일한 설명은 생략한다.",
  },
  {
    id: 9,
    menu: "곱창볶음",
    name: "곱창좋은날",
    date: "9.19~9.23",
    day: 1,
    detail: "디테일한 설명은 생략한다.",
  },
  {
    id: 10,
    menu: "칠리,크림새우",
    name: "스낵런",
    date: "9.19~9.23",
    day: 1,
    detail: "디테일한 설명은 생략한다.",
  },
];

export const fleas = [
  {
    //월화수
    id: 1,
    name: "(주)피플밤",
    date: "월~수",
    day: [1, 2, 3],
    detail: "젤라또",
  },
  {
    id: 2,
    name: "진티엔리밍",
    date: "월~수",
    day: [1, 2, 3],
    detail: "악세사리",
  },
  {
    id: 3,
    name: "원더우먼",
    date: "월~수",
    day: [1, 2, 3],
    detail: "쥬얼리",
  },
  {
    id: 4,
    name: "JiSis",
    date: "월~수",
    day: [1, 2, 3],
    detail: "쥬얼리",
  },
  {
    id: 5,
    name: "나다스토리",
    date: "월~수",
    day: [1, 2, 3],
    detail: "심리상담",
  },
  {
    id: 6,
    name: "베베시엥",
    date: "월~수",
    day: [1, 2, 3],
    detail: "펫 악세사리",
  },
  {
    id: 7,
    name: "제이얼리",
    date: "월~수",
    day: [1, 2, 3],
    detail: "악세사리",
  },
  {
    id: 8,
    name: "코지콤마",
    date: "월~수",
    day: [1, 2, 3],
    detail: "파우치",
  },
  {
    id: 9,
    name: "비쥬마켓",
    date: "월~수",
    day: [1, 2, 3],
    detail: "악세사리",
  },
  {
    id: 10,
    name: "3분 수채 초상화",
    date: "월~수",
    day: [1, 2, 3],
    detail: "캐리커쳐",
  },
  {
    id: 11,
    name: "오브제베이킹스튜디오",
    date: "월~수",
    day: [1, 2, 3],
    detail: "디저트",
  },
  {
    id: 12,
    name: "스튜디오 늘",
    date: "월~수",
    day: [1, 2, 3],
    detail: "악세사리",
  },
  {
    id: 13,
    name: "캐리커쳐",
    date: "월~수",
    day: [1, 2, 3],
    detail: "체험",
  },
  {
    id: 14,
    name: "ZEEMA",
    date: "월~수",
    day: [1, 2, 3],
    detail: "쥬얼리",
  },
  {
    id: 15,
    name: "짙은달",
    date: "월~수",
    day: [1, 2, 3],
    detail: "소품",
  },
  {
    id: 16,
    name: "밤비하우스",
    date: "월~수",
    day: [1, 2, 3],
    detail: "키덜트 캐릭터 용품",
  },
  {
    id: 17,
    name: "제이앤밸류",
    date: "월~수",
    day: [1, 2, 3],
    detail: "악세사리",
  },
  {
    id: 18,
    name: "가은 스튜디오",
    date: "월~수",
    day: [1, 2, 3],
    detail: "핸드메이드 소품",
  },
  {
    id: 19,
    name: "화이팅",
    date: "월~수",
    day: [1, 2, 3],
    detail: "빈티지",
  },
  {
    id: 20,
    name: "이소영",
    date: "월~수",
    day: [1, 2, 3],
    detail: "악세사리",
  },

  //목금
  {
    id: 1,
    name: "은율",
    date: "목~금",
    day: [4, 5],
    detail: "악세사리",
  },
  {
    id: 2,
    name: "란동산",
    date: "목~금",
    day: [4, 5],
    detail: "패션 잡화",
  },
  {
    id: 3,
    name: "(주)피플팜",
    date: "목~금",
    day: [4, 5],
    detail: "식품",
  },
  {
    id: 4,
    name: "진티엔리밍",
    date: "목~금",
    day: [4, 5],
    detail: "악세사리",
  },
  {
    id: 5,
    name: "원더우먼",
    date: "목~금",
    day: [4, 5],
    detail: "쥬얼리",
  },
  {
    id: 6,
    name: "Jisis",
    date: "목~금",
    day: [4, 5],
    detail: "쥬얼리",
  },
  {
    id: 7,
    name: "나다스토리",
    date: "목~금",
    day: [4, 5],
    detail: "심리상담",
  },
  {
    id: 8,
    name: "베베시앵",
    date: "목~금",
    day: [4, 5],
    detail: "펫 악세사리",
  },
  {
    id: 9,
    name: "제이얼리",
    date: "목~금",
    day: [4, 5],
    detail: "악세사리",
  },
  {
    id: 10,
    name: "코지콤마",
    date: "목~금",
    day: [4, 5],
    detail: "파우치",
  },
  {
    id: 11,
    name: "그릭팩토리",
    date: "목~금",
    day: [4, 5],
    detail: "식품",
  },
  {
    id: 12,
    name: "3분 수채 초상화",
    date: "목~금",
    day: [4, 5],
    detail: "캐리커쳐",
  },
  {
    id: 13,
    name: "shushu",
    date: "목~금",
    day: [4, 5],
    detail: "악세사리",
  },
  {
    id: 14,
    name: "낫뚤공방",
    date: "목~금",
    day: [4, 5],
    detail: "향수",
  },
  {
    id: 15,
    name: "빈티지리버스",
    date: "목~금",
    day: [4, 5],
    detail: "패션",
  },
  {
    id: 16,
    name: "ARO STUDIO",
    date: "목~금",
    day: [4, 5],
    detail: "헤나, 타투 스티커",
  },
  {
    id: 17,
    name: "요키네",
    date: "목~금",
    day: [4, 5],
    detail: "의류",
  },
  {
    id: 18,
    name: "이조나샵",
    date: "목~금",
    day: [4, 5],
    detail: "의류",
  },
  {
    id: 19,
    name: "허밍브래싱",
    date: "목~금",
    day: [4, 5],
    detail: "문구류",
  },
  {
    id: 20,
    name: "FeMALE DDANG",
    date: "목~금",
    day: [4, 5],
    detail: "도자기 주얼리/소품",
  },
  {
    id: 21,
    name: "샤인컬러",
    date: "목~금",
    day: [4, 5],
    detail: "의류",
  },
  {
    id: 22,
    name: "아라비티",
    date: "목~금",
    day: [4, 5],
    detail: "음료",
  },
  {
    id: 23,
    name: "취향제작실",
    date: "목~금",
    day: [4, 5],
    detail: "악세사리/잡화",
  },
  {
    id: 24,
    name: "캐리커쳐",
    date: "목~금",
    day: [4, 5],
    detail: "체험",
  },
  {
    id: 25,
    name: "스튜디오 늘",
    date: "목~금",
    day: [4, 5],
    detail: "악세사리",
  },
  {
    id: 26,
    name: "오브제 베이킹 스튜디오",
    date: "목~금",
    day: [4, 5],
    detail: "디저트",
  },
  {
    id: 27,
    name: "Carepull",
    date: "목~금",
    day: [4, 5],
    detail: "원예",
  },
  {
    id: 28,
    name: "밍블밍블",
    date: "목~금",
    day: [4, 5],
    detail: "잡화",
  },
];
